// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYWlhpwb4c2rD-w-18FbyT803A1dq-X4',
    appId: '1:597241169955:web:c48eb4bf0fb31039ea0996',
    messagingSenderId: '597241169955',
    projectId: 'apk1-flutter',
    authDomain: 'apk1-flutter.firebaseapp.com',
    storageBucket: 'apk1-flutter.appspot.com',
    measurementId: 'G-017GSCV9Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVHzoUgQBuJD4TeXkQFMKI8KFlEIVirM',
    appId: '1:597241169955:android:d4d5eff74d0cb905ea0996',
    messagingSenderId: '597241169955',
    projectId: 'apk1-flutter',
    storageBucket: 'apk1-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIs5Kb9dBW_kDZ0yDndM9PWd0OrBzM2kA',
    appId: '1:597241169955:ios:6d0e94ba2362e10bea0996',
    messagingSenderId: '597241169955',
    projectId: 'apk1-flutter',
    storageBucket: 'apk1-flutter.appspot.com',
    androidClientId: '597241169955-2otns9gaakg5eptmsgnu2h3p1u6g38kk.apps.googleusercontent.com',
    iosClientId: '597241169955-u8lv4bu49gmq7dngvblmea09stact3uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.apk1Admine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIs5Kb9dBW_kDZ0yDndM9PWd0OrBzM2kA',
    appId: '1:597241169955:ios:5fc5b1bcb09cf798ea0996',
    messagingSenderId: '597241169955',
    projectId: 'apk1-flutter',
    storageBucket: 'apk1-flutter.appspot.com',
    androidClientId: '597241169955-2otns9gaakg5eptmsgnu2h3p1u6g38kk.apps.googleusercontent.com',
    iosClientId: '597241169955-40f10klcormcof0cat5q2qetm7k05evr.apps.googleusercontent.com',
    iosBundleId: 'com.example.apk1Admine.RunnerTests',
  );
}
